title: Eduardo Copat Ratings
description: Personal ratings on media
theme: just-the-docs

url: https://eduardocopat.github.io/ratings

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

collections:
  swe_books:
    output: true
